modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL="https://github.com/botamochi129/Manual-Enchance/issues"

[[mods]]
modId = "manual_enchance"
version = "${version}"
displayName = "Manual-Enchance"
displayURL = "https://github.com/botamochi129/Manual-Enchance/"

authors = "botamochi129"
description = "Enhances the manual operation function of MTRmod."
logoFile = "icon.png"

displayTest = "IGNORE_ALL_VERSION"

[[dependencies.manual_enchance]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.manual_enchance]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.manual_enchance]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.manual_enchance]]
modId = "mtr"
mandatory = true
versionRange = "1.0"
ordering = "AFTER"
side = "BOTH"
